# Generated by Django 3.2.13 on 2022-11-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=20)),
                ('isnormal', models.BooleanField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('life', models.IntegerField()),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rankcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_path', models.TextField()),
                ('price', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='icons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battlelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=10)),
                ('my_card1_img', models.CharField(max_length=30)),
                ('my_card2_img', models.CharField(max_length=30)),
                ('my_card3_img', models.CharField(max_length=30)),
                ('enermy_nickname', models.CharField(max_length=10)),
                ('enermy_card1_img', models.CharField(max_length=30)),
                ('enermy_card2_img', models.CharField(max_length=30)),
                ('enermy_card3_img', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
